# Generated by Django 3.1.6 on 2021-02-04 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='creat_date',
            new_name='create_date',
        ),
    ]
