# Generated by Django 3.2.5 on 2021-07-12 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0003_answer_auther'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='auther',
            new_name='author',
        ),
    ]
